apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-example-spring-cloud
  namespace: secret-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-example-spring-cloud
  template:
    metadata:
      labels:
        app: secret-example-spring-cloud
    spec:
      serviceAccountName: spring-cloud-k8s-sa
      containers:
      - name: secret-example
        image: goydmitriy/secret-example-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # Enable spring cloud kubernetes config and secret using the new import way
        - name: SPRING_CONFIG_IMPORT
          value: "kubernetes:configmap/secret-app,kubernetes:secret/secret-app"
