apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-example-all
  namespace: secret-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-example-all
  template:
    metadata:
      labels:
        app: secret-example-all
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "example-role"
        vault.hashicorp.com/agent-inject-secret-vault-secret.txt: "secret/data/myapp/config"
        vault.hashicorp.com/agent-inject-template-vault-secret.txt: |
          {{ with secret "secret/data/myapp/config" }}
          db.password: {{ .Data.data.password }}
          {{ end }}
    spec:
      serviceAccountName: spring-cloud-k8s-sa
      containers:
      - name: secret-example
        image: goydmitriy/secret-example-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # 1. Env variables mapping
        - name: SECRET_CONFIG_TREE
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: secret-config-tree
        - name: SECRET_ENV_VARIABLE
          valueFrom:
            secretKeyRef:
              name: secret-app
              key: secret-env-variable
        volumeMounts:
        # 2. ConfigTree mount
        - name: configtree-volume
          mountPath: "/etc/config"
          readOnly: true
        # 3. Direct volume mount
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
        # 4. Vault sidecar mount
        - name: vault-secrets
          mountPath: /etc/vault-secrets
          readOnly: true
      - name: vault-agent
        image: hashicorp/vault:latest
        imagePullPolicy: Always
        args:
        - agent
        - -config=/etc/vault/config.hcl
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-secrets
          mountPath: /etc/vault-secrets
      volumes:
      - name: configtree-volume
        secret:
          secretName: secret-app
      - name: secret-volume
        secret:
          secretName: secret-app
          items:
          - key: secret-volume
            path: secret-volume
      - name: vault-secrets
        emptyDir: {}
      - name: vault-config
        configMap:
          name: vault-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: secret-example-all
  namespace: secret-example
spec:
  selector:
    app: secret-example-all
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: secret-example
data:
  config.hcl: |
    exit_after_auth = false
    pid_file = "/home/vault/pid"

    template {
      contents = <<EOH
      {{ with secret "secret/data/myapp/config" }}
      password: {{ .Data.data.password }}
      {{ end }}
      EOH
      destination = "/etc/vault-secrets/vault-secret.txt"
    }

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "example-role"
        }
      }

      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }

    vault {
      address = "http://vault.secret-example.svc:8200"
    }
