apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-k8s-sa
  namespace: secret-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-cloud-k8s-role
  namespace: secret-example
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-k8s-rolebinding
  namespace: secret-example
subjects:
- kind: ServiceAccount
  name: spring-cloud-k8s-sa
  namespace: secret-example
roleRef:
  kind: Role
  name: spring-cloud-k8s-role
  apiGroup: rbac.authorization.k8s.io
