apiVersion: v1
kind: Secret
metadata:
  name: secret-app
  namespace: secret-example
type: Opaque
stringData:
  secret-env-variable: "secret value for env variable"
  secret-config-tree: "secret value for config tree"
  secret-spring-k8s-api: "secret value for spring k8s api"
  secret-volume: "secret value for volume"
