apiVersion: v1
kind: Secret
metadata:
  name: secret-app
  namespace: secret-example
type: Opaque
stringData:
  # 1. Environment variable
  env-secret: "value-from-env"
  
  # 2. Volume mounted file
  volume-secret: "value-from-volume-file"
  
  # 3. ConfigTree (multiple files)
  configtree-file1: "value-from-configtree-file1"
  configtree-file2: "value-from-configtree-file2"
  
  # 4. Spring Cloud K8s API
  api-secret: "value-from-k8s-api"
