apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-injector
  namespace: secret-example
  labels:
    app: vault-agent-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-agent-injector
  template:
    metadata:
      labels:
        app: vault-agent-injector
    spec:
      containers:
      - name: sidecar-injector
        image: hashicorp/vault-k8s:latest
        imagePullPolicy: Always
        args:
        - agent-injector
        - -listen=:8080
        - -log-level=info
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vault-agent-injector-svc
  namespace: secret-example
spec:
  selector:
    app: vault-agent-injector
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
