apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-example-volume
  namespace: secret-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-example-volume
  template:
    metadata:
      labels:
        app: secret-example-volume
    spec:
      containers:
      - name: secret-example
        image: goydmitriy/secret-example-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        # 3. Mounting secret as a file
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-app
          items:
          - key: secret-volume
            path: secret-volume
